name: 'CommitHawk'
author: 'jesalg'
description: 'Notify when watched file(s) change in a GitHub repo'
branding:
  icon: 'aperture'
  color: 'orange'
inputs:
  token:
    description: GitHub Personal Access Token
    required: true    
  slack_webhook_url:
    description: 'Incoming webhook URL for Slack. This URL will be pinged when CommitHawk detects a change to the watched file(s).'
    required: false
  slack_message:
    description: 'Copy of the Slack message you want to send'
    required: false
outputs:
  commits:
    description: 'Commits containing relevant file changes'
runs:
  using: 'node12'
  main: 'dist/index.js'
