name: 'CommitHawk'
description: 'Notify when watched file(s) change in a GitHub repo'
inputs:
  slack_webhook_url:
    description: 'Incoming webhook URL for Slack. This URL will be pinged when CommitHawk detects a change to the watched file(s).'
    required: false
outputs:
  changes:
    description: 'Commit SHAs containing relevant file changes if any'
runs:
  using: 'node12'
  main: 'dist/index.js'
