name: "commit-hawk"
on:
  push:
    branches:
      - main
    paths:
      - 'test'

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        slack_webhook_url: 'http://ptsv2.com/t/9qarm-1598042741/post'
