name: "commit-hawk"
on:
  push:
    branches:
      - string-match
    paths:
      - 'test'

jobs:
  commit-hawk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      env:
        ACTIONS_STEP_DEBUG: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        slack_webhook_url: 'http://ptsv2.com/t/9qarm-1598042741/post'
        slack_message: 'Contents of the test file were changed on main'
